openapi: '3.0.2'
info:
  title: Intelli Scan
  version: '1.0'
servers:
  - url: https://intelli-scan-api.onrender.com/api
paths:
  /login:
    post:
      summary: Get Authentication token using Credential schema.
      requestBody:
        description: JSON containing credential details.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credential'
        
      responses:
        '200':
          description: A JSON containing the user id, a message and the auth token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /user:
    post:
      summary: Create a new user using UserCreate schema.
      requestBody:
        description: JSON containing details to create a new user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: JSON containing message confirming user creation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    get:
      security:
        - bearerAuth: []
      summary: Get user details using Authentication token.
      responses:
        '200':
          description: A single user's details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      security:
        - bearerAuth: []
      summary: Update user details using Authentication token.
      requestBody:
        description: JSON containing details to update a user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Confirmation of successful user detail update.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
    delete:
      security:
        - bearerAuth: []
      summary: Delete a user using Authentication token.
      responses:
        '204':
          description: Confirmation of successful user deletion.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
      

components:
  schemas:
    Credential:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    TokenResponse:
      type: object
      properties:
        user_id:
          type: integer
        message:
          type: string
        auth_token:
          type: string
    UserCreate:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    UserUpdate:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    User:
      type: object
      properties:
        user_id:
          type: integer
        name:
          type: string
        email:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oauthGoogle:
      type: oauth2
      description: This API uses OAuth2.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
            
            
    
#/login email, password
#/user email, name, password [UNPROTECTED] C || [PROTECTED] RUD
#/inference image [PROTECTED]