"""empty message

Revision ID: 0b91b99c4757
Revises: 7e4931a9e5aa
Create Date: 2024-02-09 19:28:48.592771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b91b99c4757'
down_revision = '7e4931a9e5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=True)
        batch_op.create_unique_constraint('google_id_unique', ['google_id'])
        batch_op.create_unique_constraint('email_unique', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=255),
                              nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
